# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Receiver.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 13, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 2)
        self.state = QtWidgets.QLabel(self.centralwidget)
        self.state.setObjectName("state")
        self.gridLayout.addWidget(self.state, 1, 3, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.port = QtWidgets.QLineEdit(self.centralwidget)
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 3, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.windowSize = QtWidgets.QLineEdit(self.centralwidget)
        self.windowSize.setObjectName("windowSize")
        self.gridLayout.addWidget(self.windowSize, 3, 1, 1, 1)
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 3, 3, 9, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.recv_timer = QtWidgets.QLineEdit(self.centralwidget)
        self.recv_timer.setObjectName("recv_timer")
        self.gridLayout.addWidget(self.recv_timer, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.ack_timer = QtWidgets.QLineEdit(self.centralwidget)
        self.ack_timer.setObjectName("ack_timer")
        self.gridLayout.addWidget(self.ack_timer, 5, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 8, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.cksum_errseq = QtWidgets.QLineEdit(self.centralwidget)
        self.cksum_errseq.setObjectName("cksum_errseq")
        self.gridLayout.addWidget(self.cksum_errseq, 10, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 11, 0, 1, 1)
        self.lost_errseq = QtWidgets.QLineEdit(self.centralwidget)
        self.lost_errseq.setObjectName("lost_errseq")
        self.gridLayout.addWidget(self.lost_errseq, 12, 0, 1, 2)
        self.recvButton = QtWidgets.QPushButton(self.centralwidget)
        self.recvButton.setObjectName("recvButton")
        self.gridLayout.addWidget(self.recvButton, 12, 4, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 12, 5, 1, 1)
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setObjectName("quitButton")
        self.gridLayout.addWidget(self.quitButton, 12, 6, 1, 1)
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.windowSize.raise_()
        self.recv_timer.raise_()
        self.ack_timer.raise_()
        self.label_5.raise_()
        self.comboBox.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.port.raise_()
        self.label_9.raise_()
        self.line.raise_()
        self.output.raise_()
        self.quitButton.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.label_4.raise_()
        self.state.raise_()
        self.label_8.raise_()
        self.cksum_errseq.raise_()
        self.lost_errseq.raise_()
        self.progressBar.raise_()
        self.recvButton.raise_()
        self.stopButton.raise_()
        self.timeEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 22))
        self.menubar.setObjectName("menubar")
        self.menuOPTION = QtWidgets.QMenu(self.menubar)
        self.menuOPTION.setObjectName("menuOPTION")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEXIT = QtWidgets.QAction(MainWindow)
        self.actionEXIT.setObjectName("actionEXIT")
        self.actionSAVE = QtWidgets.QAction(MainWindow)
        self.actionSAVE.setObjectName("actionSAVE")
        self.actionEXIT_2 = QtWidgets.QAction(MainWindow)
        self.actionEXIT_2.setObjectName("actionEXIT_2")
        self.actionEXIT_3 = QtWidgets.QAction(MainWindow)
        self.actionEXIT_3.setObjectName("actionEXIT_3")
        self.actionLOG = QtWidgets.QAction(MainWindow)
        self.actionLOG.setObjectName("actionLOG")
        self.menuOPTION.addAction(self.actionSAVE)
        self.menuOPTION.addSeparator()
        self.menuOPTION.addAction(self.actionLOG)
        self.menubar.addAction(self.menuOPTION.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "参数设置"))
        self.label_8.setText(_translate("MainWindow", "当前状态"))
        self.state.setText(_translate("MainWindow", "序列号:  4位     令牌数: 8    当前接收帧: 0      接收窗口: From 0 To 7"))
        self.label_9.setText(_translate("MainWindow", "端口:"))
        self.label_3.setText(_translate("MainWindow", "接收窗口大小:"))
        self.label_2.setText(_translate("MainWindow", "接收定时器:"))
        self.label.setText(_translate("MainWindow", "辅助定时器:"))
        self.label_5.setText(_translate("MainWindow", "出错控制"))
        self.comboBox.setItemText(0, _translate("MainWindow", "手工设定"))
        self.comboBox.setItemText(1, _translate("MainWindow", "随机错误"))
        self.label_6.setText(_translate("MainWindow", "出错应答帧:"))
        self.label_7.setText(_translate("MainWindow", "丢失应答帧:"))
        self.recvButton.setText(_translate("MainWindow", "开始接收"))
        self.stopButton.setText(_translate("MainWindow", "停止接收"))
        self.quitButton.setText(_translate("MainWindow", "退出"))
        self.menuOPTION.setTitle(_translate("MainWindow", "OPTION"))
        self.actionEXIT.setText(_translate("MainWindow", "EXIT"))
        self.actionSAVE.setText(_translate("MainWindow", "SAVE"))
        self.actionEXIT_2.setText(_translate("MainWindow", "EXIT"))
        self.actionEXIT_3.setText(_translate("MainWindow", "&EXIT"))
        self.actionLOG.setText(_translate("MainWindow", "LOG"))

